#!/bin/bash

# Script para compilar e iniciar storage
echo "Compilando storage..."
make 

if [ $? -eq 0 ]; then
    echo "Iniciando storage..."
    #./bin/storage ./storage.config
    #valgrind --tool=memcheck --leak-check=full --leak-resolution=high --show-leak-kinds=all --track-origins=yes --track-fds=yes --trace-children=yes --trace-children-skip='*/bin/*,*/sbin/*' --child-silent-after-fork=no --show-error-list=yes --error-limit=no --errors-for-leak-kinds=all --keep-debuginfo=yes --read-var-info=yes --read-inline-info=yes --sigill-diagnostics=yes --vgdb=no --verbose --log-file=valgrind_storage.log ./bin/storage storage.config
    valgrind --tool=memcheck --leak-check=full --leak-resolution=high --show-leak-kinds=all --track-origins=yes --track-fds=yes --trace-children=yes --trace-children-skip='*/bin/*,*/sbin/*' --child-silent-after-fork=no --show-error-list=yes --error-limit=no --errors-for-leak-kinds=all --keep-debuginfo=yes --read-var-info=yes --read-inline-info=yes --sigill-diagnostics=yes --vgdb=no --verbose --log-file=valgrind_xmaster.log strace -f -o strace_xmaster.log ./bin/storage storage.config
else
    echo "Error en la compilación del storage"
    exit 1
fi