#!/bin/bash

# Script para compilar e iniciar múltiples instancias de query
if [ $# -ne 1 ]; then
    echo "Uso: ./query <cantidad_instancias>"
    exit 1
fi

CANTIDAD=$1

echo "Compilando query_control..."
make 

if [ $? -ne 0 ]; then
    echo "Error en la compilación del query_control"
    exit 1
fi

echo "Iniciando $CANTIDAD instancias de query..."
echo ""

PIDS=""
if [ $CANTIDAD -eq 1 ]; then
    echo "Iniciando query 0 con prioridad 0 (ejecución en primer plano)"
    #./bin/query_control ./query_control.config "query_ejemplo_0" 0
    #valgrind --tool=memcheck --leak-check=full --track-origins=yes --log-file=valgrind_query0.log --show-error-list=yes --error-limit=no ./bin/query_control ./query_control.config "query_ejemplo_0" 0
    valgrind --tool=memcheck --leak-check=full --leak-resolution=high --show-leak-kinds=all --track-origins=yes --track-fds=yes --trace-children=yes --trace-children-skip='*/bin/*,*/sbin/*' --child-silent-after-fork=no --show-error-list=yes --error-limit=no --errors-for-leak-kinds=all --keep-debuginfo=yes --read-var-info=yes --read-inline-info=yes --sigill-diagnostics=yes --vgdb=no --verbose --log-file=valgrind_xquery.log strace -f -o strace_xquery.log ./bin/query_control ./query_control.config "query_ejemplo_0" 0
else
    for ((i=0; i<$CANTIDAD; i++)); do
        echo "Iniciando query $i con prioridad $i"
        ./bin/query_control ./query_control.config "query_ejemplo_$i" $i &
        PID=$!
        PIDS="$PIDS $PID"
        echo "  PID: $PID"
        sleep 1
    done

    echo "Para terminar los procesos (si no crashearon primero) se ejecuta:"
    echo "  kill $PIDS"
    echo ""
    echo "Para verificar que están ejecutándose:"
    echo "  ps -p $PIDS -o pid,cmd"
fi
