#!/bin/bash

# Validación de argumentos: Ahora pide Query, Cantidad y Prioridad
if [ $# -ne 3 ]; then
    echo "Uso: $0 <NOMBRE_QUERY> <CANTIDAD> <PRIORIDAD>"
    exit 1
fi

QUERY=$1
CANTIDAD=$2
PRIORIDAD=$3
DEMORA=0.75

# 1. Compilación silenciosa
#make --no-print-directory > /dev/null 2>&1
#if [ $? -ne 0 ]; then
#    echo "Error crítico al compilar."
#    exit 1
#fi

# 2. Aviso inicial
echo "Lanzando $CANTIDAD instancias de $QUERY con Prioridad $PRIORIDAD..."

# Trap para matar todo con Ctrl+C sin mensajes extra
trap 'kill $(jobs -p) 2>/dev/null; exit' SIGINT

# 3. Bucle de ejecución
for ((i=0; i<CANTIDAD; i++)); do
    # Ejecutamos en background (&)
    # Salida directa a consola
    # Usamos la variable $PRIORIDAD fija para todos
    ./bin/query_control ./query_control.config "$QUERY" "$PRIORIDAD" &
    sleep $DEMORA
done

# 4. Esperar en silencio
wait
