#!/bin/bash

# Script para compilar e iniciar múltiples instancias de worker
if [ $# -ne 1 ]; then
    echo "Uso: ./worker <cantidad_instancias>"
    exit 1
fi

CANTIDAD=$1
PID_FILE="worker_pids.txt"

echo "Compilando worker..."
make 

if [ $? -ne 0 ]; then
    echo "Error en la compilación del worker"
    exit 1
fi

# Limpiar archivo de PIDs
> "$PID_FILE"

PIDS=""
if [ $CANTIDAD -eq 1 ]; then
    echo "Iniciando worker 0 con ID 0 (ejecución en primer plano)"
    echo "Para terminar el proceso usar: Ctrl+C"
    echo ""
    #./bin/worker ./worker.config 0
    #valgrind --tool=memcheck --leak-check=full --track-origins=yes --log-file=valgrind_.log --show-error-list=yes --error-limit=no ./bin/worker ./worker.config 0
    valgrind --tool=memcheck --leak-check=full --leak-resolution=high --show-leak-kinds=all --track-origins=yes --track-fds=yes --trace-children=yes --trace-children-skip='*/bin/*,*/sbin/*' --child-silent-after-fork=no --show-error-list=yes --error-limit=no --errors-for-leak-kinds=all --keep-debuginfo=yes --read-var-info=yes --read-inline-info=yes --sigill-diagnostics=yes --vgdb=no --verbose --log-file=valgrind_xworker.log strace -f -o strace_xworker.log ./bin/worker ./worker.config 0
else
    for ((i=0; i<$CANTIDAD; i++)); do
        echo "Iniciando worker $i con ID $i"
        ./bin/worker ./worker.config $i &
        PID=$!
        PIDS="$PIDS $PID"
        echo "$PID" >> "$PID_FILE"  # Guardar PID en archivo
        echo "  PID: $PID"
        sleep 1
    done

    echo "Para terminar los procesos (si no crashearon primero) se ejecuta:"
    echo "  kill $PIDS"
    echo ""
    echo "Para verificar que están ejecutándose:"
    echo "  ps -p $PIDS -o pid,cmd"
    echo ""
    echo "PIDs guardados en: $PID_FILE"
fi
